# Generated by Django 4.0.5 on 2022-06-11 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='covers/')),
                ('quality', models.CharField(choices=[('480p', 'blu-ray 480p'), ('720p', 'blu-ray 720p'), ('1080p', 'blu-ray 1080p')], max_length=5)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
